app:
  name: "goDefaultCli"
  mode: "dev"
  port: 8080
log:
  level: "debug"
  filename: "go_default_cli.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: ""
  dbname: "sql_test"
  charset: "utf8mb4"
  max_open_conns: 100
  max_idle_conns: 10
redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100